version: '3.3'
services:
  web:
    build:
       context: ./php
       dockerfile: Dockerfile 
    container_name: tpdocker
    depends_on: 
        - db
    volumes:
        - ./php:/var/www/html/
    ports:
        - 8008:80
  db:
    container_name: mysqldatabase
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: tp
         MYSQL_USER: deogracia
         MYSQL_PASSWORD: eisti0001
    ports:
         - 6033:3306
    